/// build.rs — jhara-core
///
/// Drives `cbindgen` to generate `jhara_core.h` from the FFI module.
/// The header is written to `$OUT_DIR/jhara_core.h` and copied to
/// `../../swift/include/jhara_core.h` so Xcode can import it via the
/// bridging header without requiring a manual copy step.
///
/// ## Environment variables honoured
///
/// | Variable                   | Effect                              |
/// |----------------------------|-------------------------------------|
/// | `JHARA_SKIP_CBINDGEN=1`    | Skip header generation (CI fast path) |
///
/// ## Re-run triggers
///
/// Cargo re-runs this script whenever any file under `src/ffi/` changes, or
/// when `cbindgen.toml` changes.

use std::env;
use std::path::{Path, PathBuf};

fn main() {
    // ── Re-run triggers ───────────────────────────────────────────────────────
    println!("cargo:rerun-if-changed=src/ffi/");
    println!("cargo:rerun-if-changed=src/ffi/types.rs");
    println!("cargo:rerun-if-changed=src/ffi/mod.rs");
    println!("cargo:rerun-if-changed=cbindgen.toml");

    // ── Fast exit for CI environments that don't need the header ─────────────
    if env::var("JHARA_SKIP_CBINDGEN").as_deref() == Ok("1") {
        return;
    }

    let crate_dir = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR not set — this should always be set by Cargo");

    let out_dir = PathBuf::from(
        env::var("OUT_DIR").expect("OUT_DIR not set"),
    );

    let header_out = out_dir.join("jhara_core.h");

    // ── Mirrors directory for Xcode ───────────────────────────────────────────
    // Written relative to the workspace root so Xcode can find it without
    // knowing the ephemeral OUT_DIR path.
    let swift_include = PathBuf::from(&crate_dir)
        .join("../../swift/include");

    std::fs::create_dir_all(&swift_include)
        .expect("Failed to create swift/include directory");

    let swift_header = swift_include.join("jhara_core.h");

    // ── cbindgen configuration ────────────────────────────────────────────────
    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        // Prefix every exported symbol so the header is namespace-clean.
        // (cbindgen also respects the #[no_mangle] names directly.)
        include_version: true,
        autogen_warning: Some(
            "/* DO NOT EDIT — generated by build.rs via cbindgen */".into(),
        ),
        tab_width: 4,
        documentation: true,
        documentation_style: cbindgen::DocumentationStyle::C99,
        // Emit a static_assert for every struct size so Swift catches
        // layout drift at compile time (§4.4 requirement).
        usize_is_size_t: true,
        cpp_compat: false,
        // Only include items reachable from the `ffi` module.
        include_guard: Some("JHARA_CORE_H".into()),
        header: Some(concat!(
            "#include <stdint.h>\n",
            "#include <stddef.h>\n",
            "#include <stdbool.h>",
        ).into()),
        ..Default::default()
    };

    // Generate into OUT_DIR first (canonical location for build artefacts).
    cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config.clone())
        .generate()
        .expect("cbindgen failed to parse crate")
        .write_to_file(&header_out);

    // Mirror to swift/include/ for Xcode.
    std::fs::copy(&header_out, &swift_header)
        .expect("Failed to copy jhara_core.h to swift/include/");

    println!(
        "cargo:warning=jhara_core.h written to {} and mirrored to {}",
        header_out.display(),
        swift_header.display(),
    );
}
