/* DO NOT EDIT — generated by cbindgen from crates/jhara-core */
/* jhara_core.h — C FFI surface for libjhara_universal.a         */

#ifndef JHARA_CORE_H
#define JHARA_CORE_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/**
 * Discriminant values for `ScanNodeC::kind`.
 */
typedef enum NodeKind {
    NODE_KIND_UNKNOWN   = 0,
    NODE_KIND_FILE      = 1,
    NODE_KIND_DIRECTORY = 2,
    NODE_KIND_SYMLINK   = 3,
} NodeKind;

/**
 * A C-ABI-compatible representation of a single filesystem node.
 *
 * Total size: 56 bytes.  Alignment: 8 bytes.
 *
 * `path` and `name` are arena-owned; valid until `jhara_scan_free`.
 */
typedef struct ScanNodeC {
    /** NUL-terminated UTF-8 path. Arena-owned. */
    const char *path;
    /** NUL-terminated file name component. Arena-owned. */
    const char *name;
    /** Inode number. */
    uint64_t inode;
    /** Allocated disk bytes. -1 if unknown. */
    int64_t physical_size;
    /** Apparent file size. -1 if unknown. */
    int64_t logical_size;
    /** Modification time — whole seconds since UNIX epoch. */
    int64_t modification_secs;
    /** Modification time — nanosecond fraction (0–999_999_999). */
    uint32_t modification_nanos;
    /** Hard link count. */
    uint16_t link_count;
    /** Node kind — see NodeKind. */
    uint8_t kind;
    /** Reserved. Always 0. */
    uint8_t _padding;
} ScanNodeC;

/* Compile-time size guard — catches layout drift before the Swift test runs. */
_Static_assert(sizeof(ScanNodeC) == 56, "ScanNodeC size mismatch");

/**
 * A batch of scan nodes passed to the progress callback.
 *
 * Valid only for the duration of the callback invocation.
 * `count` may be zero (heartbeat / cancellation check).
 */
typedef struct ScanNodeBatchC {
    const ScanNodeC *nodes;
    size_t count;
} ScanNodeBatchC;

/**
 * Opaque scan session handle.  Never dereference from Swift.
 */
typedef struct JharaScanHandle JharaScanHandle;

/**
 * Starts an asynchronous filesystem scan.
 *
 * Returns a non-null handle on success, NULL on invalid input.
 * Caller must call `jhara_scan_free` exactly once.
 */
JharaScanHandle *jhara_scan_start(
    const char *const *roots,
    size_t root_count,
    const char *const *skip_list,
    size_t skip_count,
    void (*callback)(ScanNodeBatchC batch, void *ctx),
    void *ctx
);

/**
 * Requests cancellation.  Advisory — one more callback may fire after return.
 * Safe on NULL or already-completed handles.
 */
void jhara_scan_cancel(JharaScanHandle *handle);

/**
 * Frees all resources.  `handle` is dangling after this call.
 * Safe on NULL.
 */
void jhara_scan_free(JharaScanHandle *handle);

/**
 * Returns total physical size (bytes) under `path`, or -1 on error.
 */
int64_t jhara_tree_physical_size(JharaScanHandle *handle, const char *path);

#endif /* JHARA_CORE_H */
