// JharaApp-Bridging-Header.h
//
// Objective-C Bridging Header for JharaApp.
//
// Imported automatically by Xcode when
//   Build Settings → Swift Compiler - General →
//   Objective-C Bridging Header
// is set to:
//   $(SRCROOT)/../rust/swift/include/JharaApp-Bridging-Header.h
//
// This file exists purely to pull the cbindgen-generated C header into
// the Swift compilation unit.  Do not add application logic here.

#ifndef JharaApp_Bridging_Header_h
#define JharaApp_Bridging_Header_h

// Generated by cbindgen via crates/jhara-core/build.rs.
// Regenerated automatically on every `cargo build`.
#include "jhara_core.h"

#endif /* JharaApp_Bridging_Header_h */
