#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#ifndef JHARA_CORE_H
#define JHARA_CORE_H

/* Generated with cbindgen:0.26.0 */

/* DO NOT EDIT — generated by build.rs via cbindgen */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Opaque handle to an in-progress or completed scan session.
//
// Heap-allocated by `jhara_core_scan_start`, freed by `jhara_core_scan_free`.
// Never dereference from Swift; treat as an opaque token.
typedef struct JharaScanHandle JharaScanHandle;

// A C-ABI-compatible representation of a single filesystem node.
//
// ## Layout Contract (64 bytes, little-endian)
//
// Fields are ordered by descending alignment to produce a deterministic,
// padding-free layout on all tier-1 Rust targets (x86_64-apple-darwin,
// aarch64-apple-darwin).  The explicit `_padding` field makes the intent
// self-documenting and prevents the compiler from inserting silent bytes.
//
// | Offset | Size | Field               |
// |--------|------|---------------------|
// |  0     |  8   | path                |
// |  8     |  8   | name                |
// | 16     |  8   | inode               |
// | 24     |  8   | physical_size       |
// | 32     |  8   | logical_size        |
// | 40     |  8   | modification_secs   |
// | 48     |  4   | modification_nanos  |
// | 52     |  2   | link_count          |
// | 54     |  1   | kind                |
// | 55     |  1   | _padding            |
// | 56     |  8   | _reserved           |
//
// *cbindgen will assert the size via a `static_assert` in the generated header.
//
// ## Lifetime
//
// Both `path` and `name` point into an arena that is owned by the
// `JharaScanHandle`.  They are valid from the callback invocation until
// `jhara_scan_free` is called.  Swift consumers **must not** retain raw
// pointers past that point; copy to a `String` immediately if needed.
typedef struct ScanNodeC {
    // NUL-terminated, UTF-8 best-effort path. Arena-owned.
    const char *path;
    // NUL-terminated file name component. Arena-owned.
    const char *name;
    // Inode number as reported by `stat(2)`.
    uint64_t inode;
    // Allocated disk space in bytes (`st_blocks * 512`).  `-1` if unknown.
    int64_t physical_size;
    // Apparent file size in bytes (`st_size`).  `-1` if unknown.
    int64_t logical_size;
    // Modification time — whole seconds since UNIX epoch.
    int64_t modification_secs;
    // Modification time — nanosecond fraction (0–999_999_999).
    uint32_t modification_nanos;
    // Number of hard links (`st_nlink`).
    uint16_t link_count;
    // Node kind discriminant.  See `NodeKind` for values.
    uint8_t kind;
    // True if this is a ghost artifact (history-based).
    uint8_t is_ghost;
    // Safety tier (Safe, Caution, Risky, Blocked).
    uint8_t safety_tier;
    // Detailed safety rating (Safe, Caution with msg, Block with msg).
    uint8_t safety_rating;
    // Reserved for future use — ensures 64-byte total size.
    uint8_t _reserved[6];
} ScanNodeC;

// A fat pointer passed to the scan callback representing one batch of nodes.
//
// The batch is only valid for the duration of the callback invocation.
// The Swift callback **must** copy any data it needs before returning.
//
// `count` may be zero on a progress heartbeat; the Swift side should handle
// this gracefully (it is useful as a cancellation-check point).
typedef struct ScanNodeBatchC {
    // Pointer to the first element of a contiguous `ScanNodeC` array.
    const struct ScanNodeC *nodes;
    // Number of valid elements in `nodes`.
    size_t count;
} ScanNodeBatchC;

// Starts an asynchronous filesystem scan.
//
// ## Parameters
//
// | Parameter    | Description                                             |
// |--------------|---------------------------------------------------------|
// | `roots`      | Array of NUL-terminated UTF-8 root paths to scan       |
// | `root_count` | Length of `roots`                                       |
// | `skip_list`  | Array of NUL-terminated paths to exclude (iCloud etc.) |
// | `skip_count` | Length of `skip_list`                                   |
// | `callback`   | Called with each batch of discovered nodes              |
// | `ctx`        | Opaque context pointer forwarded to every callback      |
//
// ## Returns
//
// A non-null `*mut JharaScanHandle` on success, or **null** if:
// - `roots` is null or `root_count` is zero
// - Memory allocation fails
//
// The caller must eventually call `jhara_core_scan_free` on the returned handle.
//
// # Safety
// All pointer parameters must satisfy their documented invariants.
// The `callback` must be thread-safe (may be called from multiple threads).
struct JharaScanHandle *jhara_core_scan_start(const char *const *roots,
                                              size_t root_count,
                                              const char *const *skip_list,
                                              size_t skip_count,
                                              void (*callback)(struct ScanNodeBatchC batch,
                                                               void *ctx),
                                              void *ctx);

// Requests cancellation of an in-progress scan.
//
// This is advisory — the scan may emit one more callback batch after this
// call returns.  Safe to call multiple times; safe to call on a completed
// scan (no-op).
//
// # Safety
// `handle` must be a valid pointer returned by `jhara_scan_start` that has
// not yet been freed via `jhara_scan_free`.
void jhara_core_scan_cancel(struct JharaScanHandle *handle);

// Frees all resources associated with a scan handle.
//
// After this call `handle` is a dangling pointer; the caller must not use it.
// Passing a null pointer is a safe no-op.
//
// # Safety
// `handle` must be either null or a valid pointer returned by
// `jhara_scan_start` that has not previously been freed.
void jhara_core_scan_free(struct JharaScanHandle *handle);

// Returns the total physical size (bytes) of the subtree rooted at `path`.
//
// ## Returns
//
// - `>= 0` — cumulative `physical_size` of all nodes under `path`
// - `-1`   — `handle` or `path` is null, path not found, or scan incomplete
//
// # Safety
// `handle` must be a valid, non-freed handle.
// `path` must be a valid NUL-terminated C string or null.
int64_t jhara_core_tree_physical_size(struct JharaScanHandle *handle, const char *path);

// Deletes a list of absolute paths permanently.
//
// ## Returns
// - `0` on success
// - `-1` if `paths` is null or `count` is 0
// - `> 0` total number of errors encountered during deletion
//
// # Safety
// `paths` must be a valid array of NUL-terminated strings.
int32_t jhara_core_delete_paths(const char *const *paths, size_t count);

// Classifies a project at the given root.
// Returns a JSON string (caller must free with `jhara_core_string_free`).
char *jhara_core_project_classify(const char *project_root);

// Frees a string allocated by the core library (e.g. from `jhara_core_project_classify`).
void jhara_core_string_free(char *s);

// Returns a JSON array of all detected projects for the scanned roots.
//
// Runs `ProjectDetector` on the roots that were passed to `jhara_core_scan_start`.
// Caller must free the returned string with `jhara_core_string_free`.
// Returns null on any error.
//
// # Safety
// `handle` must be a valid non-null pointer from `jhara_core_scan_start`.
char *jhara_core_projects_results_json(const struct JharaScanHandle *handle);

// Returns a JSON array of global developer-tool caches found under `home_dir`.
//
// Physical sizes are back-filled from the scan-tree results accumulated during
// the most recent scan. Caller must free the returned string with
// `jhara_core_string_free`. Returns null on any error.
//
// # Safety
// `handle` must be a valid non-null pointer from `jhara_core_scan_start`.
// `home_dir` must be a valid NUL-terminated UTF-8 C string.
char *jhara_core_global_caches_json(const struct JharaScanHandle *handle, const char *home_dir);

#endif /* JHARA_CORE_H */
