#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

// Opaque handle to a scan session.
typedef struct JharaScanHandle JharaScanHandle;

// A C-ABI-compatible representation of a single filesystem node (64 bytes).
typedef struct ScanNodeC {
    const char *path;
    const char *name;
    uint64_t inode;
    int64_t physical_size;
    int64_t logical_size;
    int64_t modification_secs;
    uint32_t modification_nanos;
    uint16_t link_count;
    uint8_t kind;
    uint8_t is_ghost;
    uint8_t safety_tier;
    uint8_t safety_rating;
    uint8_t _reserved[6];
} ScanNodeC;

// A batch of nodes passed to the scan callback.
typedef struct ScanNodeBatchC {
    const struct ScanNodeC *nodes;
    size_t count;
} ScanNodeBatchC;


#ifndef JHARA_CORE_H
#define JHARA_CORE_H

/* Generated with cbindgen:0.26.0 */

/* DO NOT EDIT — generated by build.rs via cbindgen */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

JharaScanHandle *jhara_core_scan_start(const char *const *roots,
                                       size_t root_count,
                                       const char *const *skip_list,
                                       size_t skip_count,
                                       void (*callback)(ScanNodeBatchC batch, void *ctx),
                                       void *ctx);

void jhara_core_scan_cancel(JharaScanHandle *handle);

void jhara_core_scan_free(JharaScanHandle *handle);

int64_t jhara_core_tree_physical_size(JharaScanHandle *handle, const char *path);

int32_t jhara_core_delete_paths(const char *const *paths, size_t count);

char *jhara_core_project_classify(const char *project_root);

void jhara_core_string_free(char *s);

char *jhara_core_projects_results_json(const JharaScanHandle *handle);

char *jhara_core_global_caches_json(const JharaScanHandle *handle, const char *home_dir);

char *jhara_core_orphan_scan_json(const JharaScanHandle *handle);

#endif /* JHARA_CORE_H */
