/// build.rs — jhara-core
///
/// Drives `cbindgen` to generate `jhara_core.h` from the FFI module.
/// The header is written to `$OUT_DIR/jhara_core.h` and copied to
/// `../../swift/include/jhara_core.h` so Xcode can import it via the
/// bridging header without requiring a manual copy step.
///
/// ## Environment variables honoured
///
/// | Variable                   | Effect                              |
/// |----------------------------|-------------------------------------|
/// | `JHARA_SKIP_CBINDGEN=1`    | Skip header generation (CI fast path) |
///
/// ## Re-run triggers
///
/// Cargo re-runs this script whenever any file under `src/ffi/` changes, or
/// when `cbindgen.toml` changes.
use std::env;
use std::path::PathBuf;

fn main() {
    // ── Re-run triggers ───────────────────────────────────────────────────────
    println!("cargo:rerun-if-changed=src/ffi/");
    println!("cargo:rerun-if-changed=src/ffi/types.rs");
    println!("cargo:rerun-if-changed=src/ffi/mod.rs");
    println!("cargo:rerun-if-changed=cbindgen.toml");

    // ── Fast exit for CI environments that don't need the header ─────────────
    if env::var("JHARA_SKIP_CBINDGEN").as_deref() == Ok("1") {
        return;
    }

    let crate_dir = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR not set — this should always be set by Cargo");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));

    let header_out = out_dir.join("jhara_core.h");

    // ── Mirrors directory for Xcode ───────────────────────────────────────────
    // Written relative to the workspace root so Xcode can find it without
    // knowing the ephemeral OUT_DIR path.
    let swift_include = PathBuf::from(&crate_dir).join("../../apps/macos/include");

    std::fs::create_dir_all(&swift_include).expect("Failed to create apps/macos/include directory");

    let swift_header = swift_include.join("jhara_core.h");

    // ── cbindgen configuration ────────────────────────────────────────────────
    let mut config = cbindgen::Config::default();
    config.language = cbindgen::Language::C;
    config.include_version = true;
    config.autogen_warning = Some("/* DO NOT EDIT — generated by build.rs via cbindgen */".into());
    config.tab_width = 4;
    config.documentation = true;
    config.documentation_style = cbindgen::DocumentationStyle::C99;
    config.usize_is_size_t = true;
    config.cpp_compat = false;
    config.include_guard = Some("JHARA_CORE_H".into());
    config.header = Some(
        concat!(
            "#include <stdint.h>\n",
            "#include <stddef.h>\n",
            "#include <stdbool.h>\n\n",
            "// Opaque handle to a scan session.\n",
            "typedef struct JharaScanHandle JharaScanHandle;\n\n",
            "// A C-ABI-compatible representation of a single filesystem node (64 bytes).\n",
            "typedef struct ScanNodeC {\n",
            "    const char *path;\n",
            "    const char *name;\n",
            "    uint64_t inode;\n",
            "    int64_t physical_size;\n",
            "    int64_t logical_size;\n",
            "    int64_t modification_secs;\n",
            "    uint32_t modification_nanos;\n",
            "    uint16_t link_count;\n",
            "    uint8_t kind;\n",
            "    uint8_t is_ghost;\n",
            "    uint8_t safety_tier;\n",
            "    uint8_t safety_rating;\n",
            "    uint8_t _reserved[6];\n",
            "} ScanNodeC;\n\n",
            "// A batch of nodes passed to the scan callback.\n",
            "typedef struct ScanNodeBatchC {\n",
            "    const struct ScanNodeC *nodes;\n",
            "    size_t count;\n",
            "} ScanNodeBatchC;\n"
        )
        .into(),
    );

    // Export the types that the shim re-exports.
    config.export.include = vec![
        "JharaScanHandle".to_string(),
        "ScanNodeBatchC".to_string(),
        "ScanNodeC".to_string(),
    ];

    // Generate into OUT_DIR first (canonical location for build artefacts).
    //
    // Important: We parse `jhara-macos-ffi` (the shim), NOT `jhara-core`.
    // The shim is the only crate that carries `#[no_mangle]` — jhara-core's
    // ffi functions are `pub extern "C"` without `#[no_mangle]` so the linker
    // sees only one copy of each symbol.  cbindgen only picks up `#[no_mangle]`
    // functions, so it must be pointed at the shim crate.
    let shim_crate_dir = PathBuf::from(&crate_dir).join("../jhara-macos-ffi");

    cbindgen::Builder::new()
        .with_crate(&shim_crate_dir)
        .with_config(config.clone())
        .generate()
        .expect("cbindgen failed to parse jhara-macos-ffi shim")
        .write_to_file(&header_out);

    // Mirror to swift/include/ for Xcode.
    std::fs::copy(&header_out, &swift_header)
        .expect("Failed to copy jhara_core.h to swift/include/");

    println!(
        "cargo:warning=jhara_core.h written to {} and mirrored to {}",
        header_out.display(),
        swift_header.display(),
    );
}
